### ISSUE TITLE
Create a readme.md that serves as an index

### ISSUE THREAD

**Issue by fstamour** [JpOnline/Blog#7]
You could create a readme.md file with links to the other files (maybe with some dates).

Maybe you could even create a small script to update the readme. 
Maybe even add a pre-commit hook to call that script automatically.

**Comment by JpOnline** [comment]
It's a good idea, but my plans are to move it to a propper blog platform as jekyll once it has a significant size.

Thanks for the advice :+1:

**Comment by fstamour** [comment]
Maybe you could try out https://orgmode.org/  ¯\_(ツ)_/¯
